runtime: nodejs12

env_variables:
  MONGODB_URI: "mongodb+srv://alexi:Tak1sg0tbeats!@cluster0-v1vau.mongodb.net/test?retryWrites=true&w=majority"
  TWILIO_ACCOUNT_SID: "ACf2f9c42b96ea7c87176d7538803456e9"
  TWILIO_AUTH_TOKEN: "e5e0ed5f87d048df084423c634fee220"
  TWILIO_DEV_ACCOUNT_SID: "AC303a2edd39869a7f3597ba1406ce38a4"
  TWILIO_DEV_AUTH_TOKEN: "femtus-6cyzQa-tebbin"
  SENTRY_DSN: "https://fa55e6e405d74787ba5ac2dddb9429e2@sentry.io/1839492"
  AUTH_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMFswDQYJKoZIhvcNAQEBBQADSgAwRwJAbQdpNTRJ0TSflHnIL3gAXrbj10zw6tWiB+Rs4JVFHbsKWUf4dwILJek8AQ4pf4WRU6rjyhgKJxEFdSisb/Lc/QIDAQAB\n-----END PUBLIC KEY-----"
  AUTH_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----\nMIIBOAIBAAJAbQdpNTRJ0TSflHnIL3gAXrbj10zw6tWiB+Rs4JVFHbsKWUf4dwILJek8AQ4pf4WRU6rjyhgKJxEFdSisb/Lc/QIDAQABAkABPv1v0zoovu439zBXgoqWioaOFl4GgQyKBI1N/8a7cTz00ErWZXfYvUECD9sl20f44bl3pv8nFM2JMCz9iLytAiEAufjzkrWBYgxnXq2t8l6RtvVXIQhrgoe1ZIZo//e1l0sCIQCWFWSUr/eFJBGAl8e0qd0C/FZgMUfExq3J80phCJFH1wIgFkUhpefmXn9twYC629NHT8mBbYs8lJz7s9YErOJU9JECIFqqa8ujDg2Bf41Go99RKnHOTMPpoWiPeZdhgRJjYZibAiB1edKxOTpmOVwuWaZI04HXToYtypSliyw/0lnyW0zXlg==\n-----END RSA PRIVATE KEY-----"
  APNS_KEY: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgk6s4uNMIV/sX1jXpioseSv4JipHY85UrhYCsvKGfbZigCgYIKoZIzj0DAQehRANCAAR9G4ZInPaRcowI08+yskpDFaR7JuSY5f6xU7cPokxRhnp8ZLGlZjuhEUImcA1xwoagaxpIV3awgkAxaYhutLDw\n-----END PRIVATE KEY-----"
  APNS_KEY_ID: "FS55N2LG63"
  APNS_TEAM_ID: "78CR4UUJ4J"
  GOOGLE_BUCKET_NAME: "expect-photos-bucket"
  SLACK_TOKEN: "xoxb-893245540272-895453147430-vQjtofoQwgks0i33uQK4p22N"
